/*-----------------------------------------------
   DISPLTEXT.H -- Contains the lyric that should be displayed
  -----------------------------------------------*/

#define NUMLINES ((int) (sizeof lyric / sizeof lyric [0]))

TCHAR lyric [][70] = 
{
     TEXT ("I knew I love you - Savage Garden"),              
     TEXT (""),
	 TEXT ("Maybe it's intuition"),
	 TEXT ("But some things you just don't question"),
	 TEXT ("Like in your eyes"),
	 TEXT ("I see my future in an instant"),
	 TEXT ("And there it goes"),
	 TEXT ("I think I've found my best friend"),
	 TEXT ("I know that it might sound more than a little crazy"),
	 TEXT ("But I believe"),
	 TEXT (""),
	 TEXT ("I knew I loved you before I met you"),
	 TEXT ("I think I dreamed you into life"),
	 TEXT ("I knew I loved you before I met you"),
	 TEXT ("I have been waiting all my life")
} ;

